stages:
  - build
  - test

default:
  image: docker:latest
  services: 
    - docker:dind
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

build_docker_image:
  stage: build
  # tags:
  #   - aws-ec2 # Custom Runner
  before_script:
    - docker version
  script:
    - echo "Building the project..."
    - docker login registry.gitlab.com -u pavan0077 -p $TOKEN 
    - docker build -t registry.gitlab.com/pavan7521241/webapp-docker:$CI_PIPELINE_IID .
    - docker push registry.gitlab.com/pavan7521241/webapp-docker:$CI_PIPELINE_IID
  artifacts:
    paths:
      - $CI_PROJECT_DIR/ # GITLAB PRE-DEFINED VARIABLE
    exclude:
      - Dockerfile # This will not be added to the artifact

test_docker_image:
  stage: test
  tags:
    - aws-ec2
  script:
    - echo "Building the project..."
    - docker login registry.gitlab.com -u pavan0077 -p $TOKEN 
    - docker pull registry.gitlab.com/pavan7521241/webapp-docker:$CI_PIPELINE_IID
    - docker image ls



